version: '2'
 

services:     
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   
    ports:
      - "22000:80"
      - "22001:81"
      - "22002:443"