version: "3.0"

services:

  node1:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - ./node1:/data/db
    networks:
      - mongocluster
    command : mongod --replSet comments

  node2:
    image: mongo
    ports:
      - 30002:27017    
    volumes:
      - ./node2:/data/db
    networks:
      - mongocluster
    command : mongod --replSet comments
    depends_on :
      - node1

  node3:
    image: mongo
    ports:
      - 30003:27017     
    volumes:
      - ./node3:/data/db
    networks:
      - mongocluster
    command : mongod --replSet comments
    depends_on :
      - node1    

networks:
  mongocluster:
    driver: bridge