web:
  image: 'gitlab/gitlab-ce:latest'
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './gitlab/data:/var/opt/gitlab'


################################################################
# initial password is in init_root_password
#  change gitlab password 
#  ------------------------------------------------------------------    
#   $ docker exec -it d0bbe0e1e3db bash <-- with your CONTAINER_ID
#   
#   $ gitlab-rails console -e production
#   
#   enter image description here
#   
#   user = User.where(id: 1).first
#   user.password = 'your secret'
#   user.password_confirmation = 'your secret'
#   user.save
#   exit
################################################################
# new pass 123456789
# git config http.sslVerify "false" --->  for directory
# git clone -c http.sslVerify=false https://example.com/path/to/git
