version: '2'
 

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - ./localhost.env
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - LC_ALL=en_US.UTF-8
      - MSSQL_COLLATION=Persian_100_CI_AI
      - TZ=Asia/Tehran
    ports:
      - "1433:1433"

