#Variables
ARG IMAGENAME=mcr.microsoft.com/mssql/server
ARG VERSION=2019-latest


#Build
FROM $IMAGENAME:$VERSION

# set environment variables
#ENV SA_PASSWORD=FFF123456789#
#ENV ACCEPT_EULA=Y

EXPOSE 1433

#/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "<YourNewStrong@Passw0rd>"




